version: 2

jobs:
  build:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/cit-frontend
    steps:
      - checkout
      - run:
          command: echo $CIRCLE_TAG

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
