version: 2

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/cit-frontend
    steps:
      - checkout
      - run:
          command: echo $CIRCLE_TAG

workflows:
  version: 2
  main:
    jobs:
      - publish-github-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
